version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with docs
      - poetry run pyreverse sdc_scissor -o html -d _build/doctrees

sphinx:
   configuration: docs/conf.py
