import click
import os

@click.group()
def cli():
    pass

@cli.command()  # @cli, not @click!
def frenetic():
    click.echo('Run simulation with test case generated by Frenetic')

    command = r"python .\competition.py --visualize-tests --time-budget 10 --executor beamng --beamng-home C:\Users\birc\Documents\BeamNG.research.v1.7.0.1 --beamng-user C:\Users\birc\Documents\BeamNG.research --map-size 200 --module-name frenetic.src.generators.random_frenet_generator --class-name CustomFrenetGenerator"

    os.system(command)


if __name__ == '__main__':
    cli()
