version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2

volumes:
  influxdb:
    name: influxdb
    external: false
