name: CD

on:
  push:
    tags:
      - v*

jobs:
  cd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Check black code style
        run: |
          poetry run black -C -l 120 --check .
      - name: Test with pytest
        run: |
          poetry run pytest tests
      - name: Build package
        run: |
          poetry build
      - name: Publish package
        run: |
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
