name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    if: github.repository == 'christianbirchler-org/sdc-scissor'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - name: Copy repository
      uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python with caching
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: |
        sudo apt install python3-opengl
        poetry install
    - name: Check black code style
      run: |
        poetry run black -C -l 120 --check .
    - name: Test with pytest
      run: |
        poetry run coverage run --branch -m pytest tests
        poetry run coverage xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
